version: "3"
services:
  # Nginxコンテナ
  nginx:
    container_name: road_map_nginx
    image: nginx:alpine
    depends_on:
      - app
      - db
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl

  # アプリケーションコンテナ
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: road_map_app
    volumes:
      - ".:/server/"
    environment:
      - LC_ALL=ja_JP.UTF-8
    expose:
      - 8000
    depends_on:
      - db
    command: bash /server/docker/rundevserver.sh
    restart: always
    tty: true

  # DBコンテナ
  db:
    image: postgres:12.4-alpine
    container_name: road_map_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=road_map_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    driver: local
